//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Avia_and_Space_DeviceEntities : DbContext
    {
        public Avia_and_Space_DeviceEntities()
            : base("name=Avia_and_Space_DeviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lvl_Access> Lvl_Access { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Built_Tech> Built_Tech { get; set; }
        public virtual DbSet<Control_Type> Control_Type { get; set; }
        public virtual DbSet<Device_Type> Device_Type { get; set; }
        public virtual DbSet<Enviroment> Enviroment { get; set; }
        public virtual DbSet<Function> Function { get; set; }
        public virtual DbSet<Kind> Kind { get; set; }
        public virtual DbSet<LA_Type> LA_Type { get; set; }
        public virtual DbSet<Literature> Literature { get; set; }
        public virtual DbSet<Measure> Measure { get; set; }
        public virtual DbSet<Measure_Dims> Measure_Dims { get; set; }
        public virtual DbSet<Measure_Processing> Measure_Processing { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<Sens_Element> Sens_Element { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
