//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Enviroment = new HashSet<Enviroment>();
            this.Literature = new HashSet<Literature>();
            this.Measure = new HashSet<Measure>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_LA { get; set; }
        public Nullable<int> id_device { get; set; }
        public Nullable<int> id_kind { get; set; }
        public Nullable<int> id_se { get; set; }
        public Nullable<int> id_func { get; set; }
        public Nullable<int> id_control { get; set; }
        public Nullable<int> id_measure_proc { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<float> min_measure { get; set; }
        public Nullable<float> max_measure { get; set; }
        public Nullable<int> id_dim_measure { get; set; }
        public Nullable<float> error_measure { get; set; }
        public Nullable<float> weight { get; set; }
        public string dim_weight { get; set; }
        public Nullable<float> width { get; set; }
        public Nullable<float> length { get; set; }
        public Nullable<float> height { get; set; }
        public string dim_unit { get; set; }
        public Nullable<int> id_built_tech { get; set; }
        public Nullable<float> min_temp { get; set; }
        public Nullable<float> max_temp { get; set; }
        public string temp_unit { get; set; }
        public byte[] view { get; set; }
        public byte[] schema { get; set; }
    
        public virtual Control_Type Control_Type { get; set; }
        public virtual Device_Type Device_Type { get; set; }
        public virtual Measure_Processing Measure_Processing { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Sens_Element Sens_Element { get; set; }
        public virtual Built_Tech Built_Tech { get; set; }
        public virtual Function Function { get; set; }
        public virtual Kind Kind { get; set; }
        public virtual LA_Type LA_Type { get; set; }
        public virtual Measure_Dims Measure_Dims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enviroment> Enviroment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Literature> Literature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Measure> Measure { get; set; }
    }
}
