//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Literature()
        {
            this.Device = new HashSet<Device>();
        }
    
        public int id_lit { get; set; }
        public string lit_type { get; set; }
        public string lit_name { get; set; }
        public string lit_author { get; set; }
        public Nullable<int> lit_date { get; set; }
        public string lit_publish { get; set; }
        public string lit_web { get; set; }
        public byte[] lit_file { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Device { get; set; }
    }
}
